name: Notes
description: Eine moderne Notiz-App mit Flutter und Dart.



version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  speech_to_text: ^7.0.0
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.0.15
  timezone: ^0.9.0 # Zeitzone fÃ¼r Benachrichtigungen

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  generate: true
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart

  assets:
    - lib/assets/